services:
  - type: web
    name: music-app-backend
    env: node
    plan: free
    # 指定后端代码的相对路径
    rootDir: music-app-backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_HOST
        fromDatabase:
          name: music-app-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: music-app-db
          property: port
      - key: DATABASE_USERNAME
        fromDatabase:
          name: music-app-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: music-app-db
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: music-app-db
          property: database

databases:
  - name: music-app-db
    databaseName: music_app
    user: music_app_user
    plan: free
